#
# Module manifest for module 'AkamaiPowershell'
#
# Generated by: Stuart Macleod
#
# Generated on: 14/04/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AkamaiPowershell.psm1'

# Version number of this module.
ModuleVersion = '1.11.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a97f93ba-aa4e-433e-8949-f41fceb5866a'

# Author of this module
Author = 'Stuart Macleod'

# Company or vendor of this module
CompanyName = 'Akamai Technologies'

# Copyright statement for this module
Copyright = '(c) 2019 Akamai Technologies. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Cmdlets to manage Akamai {OPEN} APIs'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Activate-APIEndpointVersion', 'Clone-APIEndpoint', 
               'Clone-APIEndpointVersion', 'Deactivate-APIEndpointVersion', 
               'Get-APIEndpointVersion', 'Get-APIEndpointVersionCacheSettings', 
               'Get-APIEndpointVersionCorsSettings', 
               'Get-APIEndpointVersionGraphQLSettings', 
               'Get-APIEndpointVersionGZipSettings', 
               'Get-APIEndpointVersionJWTSettings', 
               'Get-APIEndpointVersionResource', 
               'Get-APIEndpointVersionRoutingSettings', 
               'Get-APIEndpointVersionSummary', 'Hide-APIEndpointVersion', 
               'List-APIEndpoints', 'List-APIEndpointVersionResources', 
               'List-APIEndpointVersions', 'New-APIEndpoint', 
               'New-APIEndpointFromFile', 'New-APIEndpointVersionResource', 
               'Remove-APIEndpoint', 'Remove-APIEndpointVersion', 
               'Remove-APIEndpointVersionResource', 'Set-APIEndpointVersion', 
               'Set-APIEndpointVersionCacheSettings', 
               'Set-APIEndpointVersionCorsSettings', 
               'Set-APIEndpointVersionFromFile', 
               'Set-APIEndpointVersionGraphQLSettings', 
               'Set-APIEndpointVersionGZipSettings', 
               'Set-APIEndpointVersionJWTSettings', 
               'Set-APIEndpointVersionResource', 
               'Set-APIEndpointVersionRoutingSettings', 'Show-APIEndpointVersion', 
               'Generate-APIKey', 'Generate-APIKeyReport', 'Get-APIKey', 
               'Get-ApiKeyCollection', 'Get-APIThrottlingCounter', 'Import-APIKey', 
               'List-APIKeyCollectionEndpoints', 'List-ApiKeyCollections', 
               'List-APIKeys', 'List-APITags', 'List-APIThrottlingCounterEndpoints', 
               'List-APIThrottlingCounterKeys', 'List-APIThrottlingCounters', 
               'Move-APIKeys', 'New-APIKey', 'New-ApiKeyCollection', 'New-APIKeys', 
               'New-APIThrottlingCounter', 'Remove-APIKeyCollection', 
               'Remove-APIThrottlingCounter', 'Reset-APIKeyQuota', 'Restore-APIKey', 
               'Revoke-APIKey', 'Set-APIKey', 'Set-APIKeyCollection', 
               'Set-ApiKeyCollectionACL', 'Set-APIKeyCollectionQuota', 
               'Set-APIThrottlingCounter', 'Activate-AppSecConfiguration', 
               'Activate-AppSecConfigurationVersion', 'Clone-AppSecSecurityPolicy', 
               'Export-AppSecConfigurationVersionDetails', 
               'Get-AppSecActivationRequestStatus', 'Get-AppSecActivationStatus', 
               'Get-AppSecBypassNetworkLists', 'Get-AppSecConfiguration', 
               'Get-AppSecConfigurationVersion', 
               'Get-AppSecConfigurationVersionDetails', 
               'Get-AppSecCustomDenyAction', 'Get-AppSecCustomRule', 
               'Get-AppSecEvasivePathMatch', 'Get-AppSecHostnameCoverage', 
               'Get-AppSecLogging', 'Get-AppSecMatchTarget', 'Get-AppSecPolicy', 
               'Get-AppSecPolicyAdaptiveIntelligence', 
               'Get-AppSecPolicyAttackGroup', 
               'Get-AppSecPolicyAttackGroupExceptions', 
               'Get-AppSecPolicyAttackGroupRecommendations', 
               'Get-AppSecPolicyEvaluationAttackGroup', 
               'Get-AppSecPolicyEvaluationAttackGroupExceptions', 
               'Get-AppSecPolicyEvaluationPenaltyBox', 
               'Get-AppSecPolicyEvaluationRule', 
               'Get-AppSecPolicyEvaluationRuleConditions', 
               'Get-AppSecPolicyEvaluationRuleExceptions', 
               'Get-AppSecPolicyEvasivePathMatch', 'Get-AppSecPolicyIPGeoFirewall', 
               'Get-AppSecPolicyLogging', 'Get-AppSecPolicyMode', 
               'Get-AppSecPolicyPenaltyBox', 'Get-AppSecPolicyPragmaSettings', 
               'Get-AppSecPolicyProtections', 'Get-AppSecPolicyReputationAnalysis', 
               'Get-AppSecPolicyReputationProfile', 
               'Get-AppSecPolicyReputationProfileAction', 
               'Get-AppSecPolicyRequestSizeLimit', 'Get-AppSecPolicyRule', 
               'Get-AppSecPolicyRuleConditions', 'Get-AppSecPolicyRuleExceptions', 
               'Get-AppSecPolicyRuleRecommendations', 
               'Get-AppSecPolicySlowPostSettings', 
               'Get-AppSecPolicyTuningRecommendations', 
               'Get-AppSecPolicyUpgradeDetails', 'Get-AppSecPragmaSettings', 
               'Get-AppSecPrefetch', 'Get-AppSecRatePolicy', 
               'Get-AppSecReputationProfile', 'Get-AppSecRequestSizeLimit', 
               'Get-AppSecSiemSettings', 'Get-AppSecSiemVersions', 
               'Get-AppSecVersionNotes', 'List-AppSecActivationHistory', 
               'List-AppSecAvailableHostnames', 'List-AppSecConfigurations', 
               'List-AppSecConfigurationVersions', 'List-AppSecCustomDenyActions', 
               'List-AppSecCustomRules', 'List-AppSecFailoverHostnames', 
               'List-AppSecHostnameOverlaps', 'List-AppSecMatchTargets', 
               'List-AppSecPolicies', 'List-AppSecPolicyAPIRequestConstraints', 
               'List-AppSecPolicyAttackGroups', 'List-AppSecPolicyCustomRules', 
               'List-AppSecPolicyEvaluationAttackGroups', 
               'List-AppSecPolicyEvaluationRules', 'List-AppSecPolicyRatePolicies', 
               'List-AppSecPolicyReputationProfileActions', 
               'List-AppSecPolicyReputationProfiles', 'List-AppSecPolicyRules', 
               'List-AppSecRatePolicies', 'List-AppSecReputationProfiles', 
               'List-AppSecSelectableHostnames', 'List-AppSecSelectedHostnames', 
               'List-AppSecSubscribers', 'New-AppSecConfiguration', 
               'New-AppSecConfigurationVersion', 'New-AppSecCustomDenyAction', 
               'New-AppSecCustomRule', 'New-AppSecMatchTarget', 'New-AppSecPolicy', 
               'New-AppSecRatePolicy', 'New-AppSecReputationProfile', 
               'New-AppSecSubscription', 'Remove-AppSecConfiguration', 
               'Remove-AppSecConfigurationVersion', 
               'Remove-AppSecCustomDenyAction', 'Remove-AppSecCustomRule', 
               'Remove-AppSecMatchTarget', 'Remove-AppSecPolicy', 
               'Remove-AppSecRatePolicy', 'Remove-AppSecReputationProfile', 
               'Remove-AppSecSubscription', 'Rename-AppSecConfiguration', 
               'Set-AppSecBypassNetworkLists', 'Set-AppSecCustomDenyAction', 
               'Set-AppSecCustomRule', 'Set-AppSecCustomRuleActions', 
               'Set-AppSecEvasivePathMatch', 'Set-AppSecLogging', 
               'Set-AppSecMatchTarget', 'Set-AppSecMatchTargetOrder', 
               'Set-AppSecPolicy', 'Set-AppSecPolicyAdaptiveIntelligence', 
               'Set-AppSecPolicyAllApiRequestConstraints', 
               'Set-AppSecPolicyAPIRequestConstraints', 
               'Set-AppSecPolicyAttackGroup', 
               'Set-AppSecPolicyAttackGroupExceptions', 
               'Set-AppSecPolicyCustomRule', 
               'Set-AppSecPolicyEvaluationAttackGroup', 
               'Set-AppSecPolicyEvaluationAttackGroupExceptions', 
               'Set-AppSecPolicyEvaluationMode', 
               'Set-AppSecPolicyEvaluationPenaltyBox', 
               'Set-AppSecPolicyEvaluationRule', 
               'Set-AppSecPolicyEvaluationRuleConditions', 
               'Set-AppSecPolicyEvaluationRuleExceptions', 
               'Set-AppSecPolicyEvasivePathMatch', 'Set-AppSecPolicyIPGeoFirewall', 
               'Set-AppSecPolicyLogging', 'Set-AppSecPolicyMode', 
               'Set-AppSecPolicyPenaltyBox', 'Set-AppSecPolicyPragmaSettings', 
               'Set-AppSecPolicyProtections', 'Set-AppSecPolicyRatePolicy', 
               'Set-AppSecPolicyRatePolicyActions', 
               'Set-AppSecPolicyReputationAnalysis', 
               'Set-AppSecPolicyReputationProfile', 
               'Set-AppSecPolicyReputationProfileAction', 
               'Set-AppSecPolicyRequestSizeLimit', 'Set-AppSecPolicyRule', 
               'Set-AppSecPolicyRuleConditions', 'Set-AppSecPolicyRuleExceptions', 
               'Set-AppSecPolicySlowPostSettings', 
               'Set-AppSecPolicyTuningRecommendations', 'Set-AppSecPragmaSettings', 
               'Set-AppSecPrefetch', 'Set-AppSecRatePolicy', 
               'Set-AppSecReputationProfile', 'Set-AppSecRequestSizeLimit', 
               'Set-AppSecSelectedHostnames', 'Set-AppSecSiemSettings', 
               'Set-AppSecVersionNotes', 'Update-AppSecKRSRuleSet', 
               'Get-ProductUsage', 'Get-ProductUsagePerDay', 
               'Get-ProductUsagePerMonth', 
               'Get-AppSecPolicyAkamaiBotCategoryAction', 
               'Get-AppSecPolicyBotDetectionAction', 
               'Get-AppSecPolicyCustomBotCategoryAction', 
               'Get-AppSecPolicyTransactionalEndpoint', 
               'Get-BotManAkamaiBotCategory', 'Get-BotManAkamaiDefinedBot', 
               'Get-BotManBotAnalyticsCookieSettings', 
               'Get-BotManBotAnalyticsCookieValues', 'Get-BotManBotDetection', 
               'Get-BotManChallengeAction', 'Get-BotManClientSideSecurity', 
               'Get-BotManConditionalAction', 
               'Get-BotManConfigBotEndpointCoverageReport', 
               'Get-BotManCustomBotCategory', 
               'Get-BotManCustomBotCategorySequence', 'Get-BotManCustomClient', 
               'Get-BotManCustomDefinedBot', 'Get-BotManCustomDenyAction', 
               'Get-BotManRecategorizedAkamaiDefinedBot', 
               'Get-BotManServeAlternateAction', 
               'List-AppSecPolicyAkamaiBotCategoryActions', 
               'List-AppSecPolicyBotCategoryExceptions', 
               'List-AppSecPolicyBotDetectionActions', 
               'List-AppSecPolicyBotManagementSettings', 
               'List-AppSecPolicyCustomBotCategoryActions', 
               'List-AppSecPolicyJavascriptInjection', 
               'List-AppSecPolicyTransactionalEndpoints', 
               'List-BotManAkamaiBotCategories', 'List-BotManAkamaiDefinedBots', 
               'List-BotManBotDetections', 'List-BotManBotEndpointCoverageReports', 
               'List-BotManChallengeActions', 
               'List-BotManChallengeInterceptionRules', 
               'List-BotManConditionalActions', 'List-BotManCustomBotCategories', 
               'List-BotManCustomClients', 'List-BotManCustomDefinedBots', 
               'List-BotManCustomDenyActions', 
               'List-BotManRecategorizedAkamaiDefinedBots', 
               'List-BotManResponseActions', 'List-BotManServeAlternateActions', 
               'List-BotManTransactionalEndpointProtections', 
               'Move-BotManAkamaiDefinedBot', 
               'Move-BotManRecategorizedAkamaiDefinedBot', 
               'New-AppSecPolicyTransactionalEndpoint', 
               'New-BotManChallengeAction', 'New-BotManConditionalAction', 
               'New-BotManCustomBotCategory', 'New-BotManCustomClient', 
               'New-BotManCustomDefinedBot', 'New-BotManCustomDenyAction', 
               'New-BotManServeAlternateAction', 
               'Remove-AppSecPolicyTransactionalEndpoint', 
               'Remove-BotManChallengeAction', 'Remove-BotManConditionalAction', 
               'Remove-BotManCustomBotCategory', 'Remove-BotManCustomClient', 
               'Remove-BotManCustomDefinedBot', 'Remove-BotManCustomDenyAction', 
               'Remove-BotManRecategorizedAkamaiDefinedBot', 
               'Remove-BotManServeAlternateAction', 
               'Set-AppSecPolicyAkamaiBotCategoryAction', 
               'Set-AppSecPolicyBotCategoryExceptions', 
               'Set-AppSecPolicyBotDetectionAction', 
               'Set-AppSecPolicyBotManagementSettings', 
               'Set-AppSecPolicyCustomBotCategoryAction', 
               'Set-AppSecPolicyJavascriptInjection', 
               'Set-AppSecPolicyTransactionalEndpoint', 
               'Set-BotManBotAnalyticsCookieSettings', 'Set-BotManChallengeAction', 
               'Set-BotManChallengeInterceptionRules', 
               'Set-BotManClientSideSecurity', 'Set-BotManConditionalAction', 
               'Set-BotManCustomBotCategory', 
               'Set-BotManCustomBotCategorySequence', 'Set-BotManCustomClient', 
               'Set-BotManCustomDefinedBot', 'Set-BotManCustomDenyAction', 
               'Set-BotManServeAlternateAction', 
               'Set-BotManTransactionalEndpointProtections', 
               'Update-BotManBotAnalyticsCookieValues', 'Get-AccessKey', 
               'Get-AccessKeyCreateRequest', 'Get-AccessKeyVersion', 
               'Get-AccessKeyVersionCreateRequest', 
               'Get-AccessKeyVersionProperties', 'Get-AccessKeyVersionStatus', 
               'List-AccessKeys', 'List-AccessKeyVersions', 'New-AccessKey', 
               'New-AccessKeyVersion', 'Remove-AccessKeyVersion', 'Purge-Cache', 
               'Get-ChinaCDNDeprovisionPolicy', 'Get-ChinaCDNPropertyHostname', 
               'Get-ChinaCDNProvisionStateChange', 'List-ChinaCDNEdgeHostnames', 
               'List-ChinaCDNGroups', 'List-ChinaCDNHoldingEntities', 
               'List-ChinaCDNICPNumbers', 'List-ChinaCDNPropertyHostnames', 
               'List-ChinaCDNProvisionStateChanges', 
               'List-ChinaCDNProvisionStates', 'New-ChinaCDNPropertyHostname', 
               'New-ChinaCDNProvisionStateChange', 'Set-ChinaCDNDeprovisionPolicy', 
               'Set-ChinaCDNPropertyHostname', 
               'Activate-CloudletLoadBalancingVersion', 
               'Activate-CloudletPolicyVersion', 'Activate-SharedCloudletPolicy', 
               'Copy-SharedCloudletPolicy', 'Download-CloudletPolicyVersion', 
               'Get-Cloudlet', 'Get-CloudletConditionalOrigin', 'Get-CloudletGroup', 
               'Get-CloudletLoadBalancer', 'Get-CloudletLoadBalancingVersion', 
               'Get-CloudletPolicy', 'Get-CloudletPolicyAssociatedProperties', 
               'Get-CloudletPolicyVersion', 'Get-CloudletPolicyVersionRule', 
               'Get-CloudletSchema', 'Get-SharedCloudletPolicy', 
               'Get-SharedCloudletPolicyActivation', 
               'Get-SharedCloudletPolicyProperties', 
               'Get-SharedCloudletPolicyVersion', 
               'List-CloudletAssociatedProperties', 
               'List-CloudletConditionalOrigins', 
               'List-CloudletCurrentLoadBalancingActivations', 
               'List-CloudletGroups', 'List-CloudletLoadBalancers', 
               'List-CloudletLoadBalancingActivations', 
               'List-CloudletLoadBalancingVersions', 'List-CloudletPolicies', 
               'List-CloudletPolicyActivations', 'List-CloudletPolicyVersions', 
               'List-Cloudlets', 'List-CloudletSchemas', 
               'List-SharedCloudletPolicies', 
               'List-SharedCloudletPolicyActivations', 
               'List-SharedCloudletPolicyVersions', 'List-SharedCloudlets', 
               'New-CloudletLoadBalancer', 'New-CloudletLoadBalancingVersion', 
               'New-CloudletPolicy', 'New-CloudletPolicyVersion', 
               'New-CloudletPolicyVersionRule', 'New-SharedCloudletPolicy', 
               'New-SharedCloudletPolicyVersion', 'Remove-CloudletPolicy', 
               'Remove-SharedCloudletPolicy', 'Remove-SharedCloudletPolicyVersion', 
               'Set-CloudletConditionalOrigin', 'Set-CloudletLoadBalancer', 
               'Set-CloudletLoadBalancingVersion', 'Set-CloudletPolicyVersion', 
               'Set-CloudletPolicyVersionRule', 'Set-SharedCloudletPolicy', 
               'Set-SharedCloudletPolicyVersion', 'Get-GTMDomain', 
               'Get-GTMDomainASMap', 'Get-GTMDomainCurrentStatus', 
               'Get-GTMDomainDatacenter', 'Get-GTMDomainGeoMap', 
               'Get-GTMDomainProperty', 'Get-GTMDomainResource', 
               'List-GTMDomainASMaps', 'List-GTMDomainDatacenters', 
               'List-GTMDomainGeoMaps', 'List-GTMDomainProperties', 
               'List-GTMDomainResources', 'List-GTMDomains', 
               'New-GTMDefaultDatacenter', 'New-GTMDomain', 'Remove-GTMDomainASMap', 
               'Remove-GTMDomainDatacenter', 'Remove-GTMDomainGeoMap', 
               'Remove-GTMDomainProperty', 'Remove-GTMDomainResource', 
               'Set-GTMDomainASMap', 'Set-GTMDomainDatacenter', 
               'Set-GTMDomainGeoMap', 'Set-GTMDomainProperty', 
               'Set-GTMDomainResource', 'List-Contracts', 'List-ProductsPerContract', 
               'Get-CPCode', 'Get-CPReportingGroup', 'List-CPCodes', 
               'List-CPCodeWatermarkLimits', 'List-CPReportingGroups', 
               'List-CPReportingGroupWatermarkLimits', 'New-CPReportingGroup', 
               'Remove-CPReportingGroup', 'Rename-CPCode', 'Set-CPCode', 
               'Set-CPReportingGroup', 'Get-CPSCertificateHistory', 
               'Get-CPSChangeHistory', 'Get-CPSDVHistory', 'Get-CPSEnrollment', 
               'List-CPSDeployments', 'List-CPSEnrollments', 
               'List-CPSProductionDeployments', 'List-CPSStagingDeployments', 
               'New-CPSEnrollment', 'Remove-CPSEnrollment', 'Set-CPSEnrollment', 
               'List-CtrAPIContracts', 'List-CtrAPIProductsPerContract', 
               'List-CtrApiProductsPerReportingGroup', 
               'List-CtrApiReportingGroupIDs', 'List-CtrApiReportingGroups', 
               'Activate-DataStream', 'Deactivate-DataStream', 'Get-DataStream', 
               'Get-DataStreamActivationHistory', 'Get-DataStreamHistory', 
               'Get-DatastreamMigrationPayload', 'Get-DataStreamVersion', 
               'List-DatastreamConnectors', 'List-DatastreamDatasetFields', 
               'List-DatastreamGroups', 'List-DatastreamProducts', 
               'List-DataStreamProperties', 'List-DataStreams', 
               'List-DataStreamTypes', 'New-DataStream', 'New-DatastreamMigration', 
               'Remove-DataStream', 'Set-DataStream', 'Find-IPAddress', 
               'Get-DiagnosticGroupData', 'Get-EdgeErrorStatistics', 'Get-EdgeLogs', 
               'Get-ErrorTranslation', 'Get-MetadataTrace', 'Get-URLTranslation', 
               'List-DiagnosticsGroups', 'List-EdgeLocations', 
               'List-IPAccelerationHostnames', 'New-DiagnosticLink', 'New-EdgeCurl', 
               'New-EdgeDig', 'New-EdgeMTR', 'New-ErrorTranslation', 
               'New-MetadataTrace', 'Test-EdgeIP', 'Get-BulkZoneDeleteResult', 
               'Get-BulkZoneDeleteStatus', 'Get-MasterZoneFile', 'Get-RecordSet', 
               'Get-RecordSetTypes', 'Get-Zone', 'Get-ZoneAliases', 'Get-ZoneContract', 
               'Get-ZoneDNSSecStatus', 'Get-ZoneRecordSetNames', 
               'Get-ZoneRecordSets', 'Get-ZoneTransferStatus', 'List-RecordSets', 
               'List-TSIGKeys', 'List-Zones', 'New-BulkZoneDeleteRequest', 
               'New-MultipleRecordSets', 'New-RecordSet', 'New-Zone', 
               'Remove-RecordSet', 'Set-MasterZoneFile', 'Set-MultipleRecordSets', 
               'Set-RecordSet', 'Set-Zone', 'Get-EdgeKVAccessToken', 'Get-EdgeKVGroup', 
               'Get-EdgeKVInitializationStatus', 'Get-EdgeKVItem', 
               'Get-EdgeKVNamespace', 'Initialize-EdgeKV', 'List-EdgeKVAccessTokens', 
               'List-EdgeKVGroups', 'List-EdgeKVItems', 'List-EdgeKVNamespaces', 
               'Move-EdgeKVNamespace', 'New-EdgeKVAccessToken', 'New-EdgeKVItem', 
               'New-EdgeKVNamespace', 'Remove-EdgeKVAccessToken', 
               'Remove-EdgeKVItem', 'Set-EdgeKVNamespace', 'Update-EdgeKVNamespace', 
               'Activate-EdgeWorker', 'Copy-EdgeWorker', 'Deactivate-EdgeWorker', 
               'Get-EdgeWorker', 'Get-EdgeWorkerActivation', 
               'Get-EdgeWorkerAuthToken', 'Get-EdgeWorkerCodeBundle', 
               'Get-EdgeWorkerDeactivation', 'Get-EdgeWorkerGroup', 
               'Get-EdgeWorkerReport', 'Get-EdgeWorkerResourceTier', 
               'Get-EdgeWorkerVersion', 'List-EdgeWorkerActivations', 
               'List-EdgeWorkerContracts', 'List-EdgeWorkerDeactivations', 
               'List-EdgeWorkerGroups', 'List-EdgeWorkerLimits', 
               'List-EdgeWorkerProperties', 'List-EdgeWorkerReports', 
               'List-EdgeWorkerResourceTiers', 'List-EdgeWorkers', 
               'List-EdgeWorkerVersions', 'New-EdgeWorker', 
               'New-EdgeWorkerAuthToken', 'New-EdgeWorkerSecret', 
               'New-EdgeWorkerVersion', 'Remove-EdgeWorker', 
               'Remove-EdgeWorkerActivation', 'Remove-EdgeWorkerVersion', 
               'Set-EdgeWorker', 'Undo-EdgeWorkerActivation', 
               'Validate-EdgeWorkerCodeBundle', 'Get-FRMService', 
               'List-FRMCidrBlocks', 'List-FRMServices', 'Get-GTMDatacenterLatency', 
               'Get-GTMLivenessPerProperty', 'Get-GTMLivenessTestError', 
               'Get-GTMLoadData', 'Get-GTMTrafficPerDatacenter', 
               'Get-GTMTrafficPerProperty', 'List-GTMLivenessTestErrors', 
               'Set-GTMLoadData', 'Get-EdgeHostname', 'Get-EdgeHostnameByDNS', 
               'Get-EdgeHostnameCertificate', 'Get-EdgeHostnameChangeRequest', 
               'Get-EdgeHostnameLocalizationData', 
               'List-EdgeHostnameChangeRequests', 
               'List-EdgeHostnameChangeRequestsForHostname', 
               'List-EdgeHostnameProducts', 'List-EdgeHostnames', 
               'Remove-EdgeHostname', 'Set-EdgeHostname', 
               'Get-IDMClientByAccessToken', 'Get-IDMGroup', 'Get-IDMProperty', 
               'Get-IDMRole', 'Get-IDMUser', 'Get-IDMUserProfile', 
               'List-IDMAccountSwitchKeys', 'List-IDMGrantableRoles', 
               'List-IDMGroupMoveAffectedUsers', 'List-IDMGroups', 
               'List-IDMProperties', 'List-IDMPropertyResources', 'List-IDMRoles', 
               'List-IDMUsers', 'List-IDMUsersForProperty', 'New-IDMGroup', 
               'New-IDMRole', 'New-IDMUser', 'Remove-IDMGroup', 'Set-IDMGroupName', 
               'Set-IDMProperty', 'Set-IDMUserAuthGrants', 'Get-ImageManagerImage', 
               'Get-ImageManagerImageCollection', 
               'Get-ImageManagerImageCollectionHistory', 'Get-ImageManagerPolicy', 
               'Get-ImageManagerPolicyHistory', 'Get-IVMPolicySet', 
               'List-ImageManagerImageCollections', 'List-ImageManagerImages', 
               'List-ImageManagerPolicies', 'New-ImageManagerPolicy', 
               'New-IVMPolicySet', 'Remove-ImageManagerImageCollection', 
               'Remove-ImageManagerPolicy', 'Remove-IVMPolicySet', 
               'Rollback-ImageManagerPolicy', 'Set-ImageManagerPolicy', 
               'Set-IVMPolicySet', 'Find-LDSLogFormat', 'Get-LDSContact', 
               'Get-LDSDeliveryFrequency', 'Get-LDSDeliveryThreshold', 
               'Get-LDSLogConfiguration', 'Get-LDSLogEncoding', 'Get-LDSLogFormat', 
               'Get-LDSLogRedelivery', 'Get-LDSLogSource', 'Get-LDSMessageSize', 
               'List-LDSContacts', 'List-LDSDeliveryFrequencies', 
               'List-LDSDeliveryThresholds', 'List-LDSLogConfigurations', 
               'List-LDSLogConfigurationsByType', 'List-LDSLogConfigurationsForID', 
               'List-LDSLogEncodings', 'List-LDSLogFormats', 
               'List-LDSLogFormatsByType', 'List-LDSLogRedeliveries', 
               'List-LDSLogSources', 'List-LDSLogSourcesByType', 
               'List-LDSMessageSizes', 'New-LDSLogConfiguration', 
               'New-LDSLogRedelivery', 'Remove-LDSLogConfiguration', 
               'Resume-LDSLogConfiguration', 'Set-LDSLogConfiguration', 
               'Suspend-LDSLogConfiguration', 'Get-AMDDataStore', 
               'Get-AMDDeliveryData', 'Get-AMDRealTimeData', 'List-AMDDataStores', 
               'Get-MSLOrigin', 'Get-MSLStream', 'List-MSLCDNs', 'List-MSLContracts', 
               'List-MSLCPCodes', 'List-MSLOriginCPCodes', 'List-MSLOrigins', 
               'List-MSLPublishingLocations', 'List-MSLStreams', 
               'List-MSLVODOrigins', 'New-MSLCPCode', 'New-MSLKey', 'New-MSLOrigin', 
               'New-MSLStream', 'Remove-MSLOrigin', 'Remove-MSLStream', 
               'Set-MSLOrigin', 'Set-MSLStream', 'Get-NSStorageGroup', 
               'Get-NSUploadAccount', 'List-NSStorageGroups', 
               'List-NSUploadAccounts', 'List-NSZones', 'New-NSStorageGroup', 
               'New-NSUploadAccount', 'Set-NSStorageGroup', 'Set-NSUploadAccount', 
               'Activate-NetworkList', 'AddTo-NetworkList', 'Append-NetworkList', 
               'Get-NetworkList', 'Get-NetworkListActivationStatus', 
               'List-NetworkLists', 'New-NetworkList', 'Remove-NetworkList', 
               'RemoveFrom-NetworkList', 'Set-NetworkList', 
               'Dir-NetstorageDirectory', 'Download-NetstorageFile', 
               'Du-NetstorageDirectory', 'List-NetstorageDirectory', 
               'New-NetstorageDirectory', 'Remove-NetstorageDirectory', 
               'Remove-NetstorageFile', 'Rename-NetstorageFile', 
               'Set-NetstorageFileMTime', 'Stat-NetstorageObject', 
               'Symlink-NetstorageObject', 'Upload-NetstorageFile', 
               'Activate-BulkProperties', 'Activate-Property', 
               'Activate-PropertyInclude', 'Add-BucketHostnames', 
               'Add-PropertyHostnames', 'Compare-BucketHostnames', 
               'Deactivate-Property', 'Deactivate-PropertyInclude', 'Find-Property', 
               'Get-AccountID', 'Get-BucketActivation', 'Get-BulkSearchResults', 
               'Get-CustomBehavior', 'Get-Group', 'Get-GroupByName', 
               'Get-LatestVersionOfProperty', 'Get-PapiClientSettings', 
               'Get-PapiCPCode', 'Get-PapiEdgeHostname', 'Get-Property', 
               'Get-PropertyActivation', 'Get-PropertyInclude', 
               'Get-PropertyIncludeActivation', 'Get-PropertyIncludeRuleTemplates', 
               'Get-PropertyIncludeRuleTree', 'Get-PropertyIncludeVersion', 
               'Get-PropertyRuleTemplates', 'Get-PropertyRuleTree', 
               'Get-PropertyTemplates', 'Get-PropertyVersion', 
               'Get-RuleFormatSchema', 'List-AllProperties', 
               'List-BucketActivations', 'List-BucketHostnames', 
               'List-BulkActivatedProperties', 'List-BulkPatchedProperties', 
               'List-BulkVersionedProperties', 'List-CustomBehaviors', 'List-Groups', 
               'List-PapiContracts', 'List-PapiCPCodes', 'List-PapiEdgeHostnames', 
               'List-Products', 'List-Properties', 'List-PropertyActivations', 
               'List-PropertyHostnames', 'List-PropertyIncludeActivations', 
               'List-PropertyIncludes', 'List-PropertyIncludeVersions', 
               'List-PropertyVersions', 'List-RuleFormats', 'List-TopLevelGroups', 
               'Merge-PropertyRuleTemplates', 'New-BulkActivation', 'New-BulkPatch', 
               'New-BulkSearch', 'New-BulkVersion', 'New-CPCode', 'New-EdgeHostname', 
               'New-Property', 'New-PropertyInclude', 'New-PropertyIncludeVersion', 
               'New-PropertyVersion', 'Remove-BucketActivation', 
               'Remove-BucketHostnames', 'Remove-Property', 
               'Remove-PropertyHostnames', 'Remove-PropertyInclude', 
               'Set-PAPIClientSettings', 'Set-PropertyHostnames', 
               'Set-PropertyIncludeRuleTemplates', 'Set-PropertyIncludeRuleTree', 
               'Set-PropertyRuleTemplates', 'Set-PropertyRuleTree', 
               'Generate-Report', 'Get-CacheableReport', 'Get-ReportType', 
               'List-ReportTypes', 'List-ReportTypeVersions', 'Crypto', 
               'Decode-Base64String', 'Decode-URL', 'Get-AkamaiCredentials', 
               'Get-AkamaiSession', 'Get-NetstorageCredentials', 
               'Get-OSSlashCharacter', 'Get-RandomString', 
               'Invoke-AkamaiNSAPIRequest', 'Invoke-AkamaiRestMethod', 
               'New-AkamaiSession', 'New-EdgeAuthToken', 'Parse-EdgercFile', 
               'Parse-NSAuthFile', 'Remove-AkamaiSession', 
               'Remove-NullQueryParameters', 'Sanitize-Filename', 
               'Sanitize-QueryString', 'Set-AkamaiSession', 'Test-Auth', 
               'Test-OpenApi', 'Verify-Auth', 'Get-SIEMData', 'Parse-SIEMEvent', 
               'Acknowledge-SiteShieldMapByID', 'Get-SiteShieldMapByID', 
               'List-SiteShieldMaps', 'Get-SLATestConfiguration', 
               'List-SLAAvailabilityReports', 'List-SLAPerformanceReports', 
               'List-SLATestAgentGroups', 'List-SLATestConfigurationQuotas', 
               'List-SLATestConfigurations', 'New-SLATestConfiguration', 
               'Remove-SLATestConfiguration', 'Set-SLATestConfiguration', 
               'Activate-TCMSet', 'Get-TCMSet', 'Get-TCMSetCertificate', 
               'Get-TCMSetDeployments', 'Get-TCMSetVersion', 
               'Get-TCMSetVersionDeployment', 'List-TCMSetCertificateIDs', 
               'List-TCMSetCertificates', 'List-TCMSets', 'List-TCMSetTrustChains', 
               'List-TCMSetVersionCertificateIDs', 
               'List-TCMSetVersionCertificates', 'List-TCMSetVersions', 'New-TCMSet', 
               'Remove-TCMSet', 'Validate-TCMSet', 'Add-TestCasesToTestSuite', 
               'Add-TestRequirementToTestSuites', 'Get-TestCatalogTemplate', 
               'Get-TestClientProfile', 'Get-TestCondition', 'Get-TestConfigVersion', 
               'Get-TestDefinition', 'Get-TestExecution', 'Get-TestRequest', 
               'Get-TestRequirement', 'Get-TestRun', 'Get-TestSuite', 
               'List-TestCasesInTestSuite', 'List-TestClientProfiles', 
               'List-TestClientProfileTestCases', 'List-TestConditions', 
               'List-TestConfigVersions', 'List-TestDefinitions', 
               'List-TestExecutions', 'List-TestRequests', 
               'List-TestRequestTestCases', 'List-TestRequirements', 
               'List-TestRequirementTestSuites', 'List-TestRuns', 
               'List-TestSuiteConfigVersions', 'List-TestSuiteRequirements', 
               'List-TestSuites', 'List-TestSuiteTestCases', 'New-TestCondition', 
               'New-TestConfigVersion', 'New-TestDefinition', 'New-TestRequest', 
               'New-TestRequests', 'New-TestRequirement', 'New-TestRun', 
               'New-TestSuite', 'Remove-TestCasesFromTestSuite', 
               'Remove-TestCondition', 'Remove-TestConfigVersion', 
               'Remove-TestDefinition', 'Remove-TestRequest', 
               'Remove-TestRequirement', 'Remove-TestRequirementFromTestSuites', 
               'Remove-TestSuite', 'Restore-TestCondition', 
               'Restore-TestConfigVersion', 'Restore-TestDefinition', 
               'Restore-TestRequest', 'Restore-TestRequirement', 'Restore-TestSuite', 
               'Set-TestCondition', 'Set-TestDefinition', 'Set-TestRequest', 
               'Set-TestRequirement', 'Set-TestSuite'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-APIEndpoints', 'Get-APIEndpointVersionResources', 
               'Get-APIEndpointVersions', 'Get-APIKeyCollectionEndpoints', 
               'Get-ApiKeyCollections', 'Get-APIKeys', 'Get-APITags', 
               'Get-APIThrottlingCounterEndpoints', 'Get-APIThrottlingCounterKeys', 
               'Get-APIThrottlingCounters', 'Get-AppSecActivationHistory', 
               'Get-AppSecAvailableHostnames', 'Get-AppSecConfigurations', 
               'Get-AppSecConfigurationVersions', 'Get-AppSecCustomDenyActions', 
               'Get-AppSecCustomRules', 'Get-AppSecFailoverHostnames', 
               'Get-AppSecHostnameOverlaps', 'Get-AppSecMatchTargets', 
               'Get-AppSecPolicies', 'Get-AppSecPolicyAPIRequestConstraints', 
               'Get-AppSecPolicyAttackGroups', 'Get-AppSecPolicyCustomRules', 
               'Get-AppSecPolicyEvaluationAttackGroups', 
               'Get-AppSecPolicyEvaluationRules', 'Get-AppSecPolicyRatePolicies', 
               'Get-AppSecPolicyReputationProfileActions', 
               'Get-AppSecPolicyReputationProfiles', 'Get-AppSecPolicyRules', 
               'Get-AppSecRatePolicies', 'Get-AppSecReputationProfiles', 
               'Get-AppSecSelectableHostnames', 'Get-AppSecSelectedHostnames', 
               'Get-AppSecSubscribers', 'Get-AppSecPolicyAkamaiBotCategoryActions', 
               'Get-AppSecPolicyBotCategoryExceptions', 
               'Get-AppSecPolicyBotDetectionActions', 
               'Get-AppSecPolicyBotManagementSettings', 
               'Get-AppSecPolicyCustomBotCategoryActions', 
               'Get-AppSecPolicyJavascriptInjection', 
               'Get-AppSecPolicyTransactionalEndpoints', 
               'Get-BotManAkamaiBotCategories', 'Get-BotManAkamaiDefinedBots', 
               'Get-BotManBotDetections', 'Get-BotManBotEndpointCoverageReports', 
               'Get-BotManChallengeActions', 
               'Get-BotManChallengeInterceptionRules', 
               'Get-BotManConditionalActions', 'Get-BotManCustomBotCategories', 
               'Get-BotManCustomClients', 'Get-BotManCustomDefinedBots', 
               'Get-BotManCustomDenyActions', 
               'Get-BotManRecategorizedAkamaiDefinedBots', 
               'Get-BotManResponseActions', 'Get-BotManServeAlternateActions', 
               'Get-BotManTransactionalEndpointProtections', 'Get-AccessKeys', 
               'Get-AccessKeyVersions', 'Get-ChinaCDNEdgeHostnames', 
               'Get-ChinaCDNGroups', 'Get-ChinaCDNHoldingEntities', 
               'Get-ChinaCDNICPNumbers', 'Get-ChinaCDNPropertyHostnames', 
               'Get-ChinaCDNProvisionStateChanges', 'Get-ChinaCDNProvisionStates', 
               'Get-CloudletAssociatedProperties', 
               'Get-CloudletConditionalOrigins', 
               'Get-CloudletCurrentLoadBalancingActivations', 'Get-CloudletGroups', 
               'Get-CloudletLoadBalancers', 'Get-CloudletLoadBalancingActivations', 
               'Get-CloudletLoadBalancingVersions', 'Get-CloudletPolicies', 
               'Get-CloudletPolicyActivations', 'Get-CloudletPolicyVersions', 
               'Get-Cloudlets', 'Get-CloudletSchemas', 'Get-SharedCloudletPolicies', 
               'Get-SharedCloudletPolicyActivations', 
               'Get-SharedCloudletPolicyVersions', 'Get-SharedCloudlets', 
               'Get-GTMDomainASMaps', 'Get-GTMDomainDatacenters', 
               'Get-GTMDomainGeoMaps', 'Get-GTMDomainProperties', 
               'Get-GTMDomainResources', 'Get-GTMDomains', 'New-GTMDomainASMap', 
               'New-GTMDomainDatacenter', 'New-GTMDomainGeoMap', 
               'New-GTMDomainProperty', 'New-GTMDomainResource', 'Get-Contracts', 
               'Get-ProductsPerContract', 'Get-CPCodes', 'Get-CPCodeWatermarkLimits', 
               'Get-CPReportingGroups', 'Get-CPReportingGroupWatermarkLimits', 
               'Get-CPSDeployments', 'Get-CPSEnrollments', 
               'Get-CPSProductionDeployments', 'Get-CPSStagingDeployments', 
               'Get-CtrAPIContracts', 'Get-CtrAPIProductsPerContract', 
               'Get-CtrApiProductsPerReportingGroup', 
               'Get-CtrApiReportingGroupIDs', 'Get-CtrApiReportingGroups', 
               'Activate-DS2Stream', 'Deactivate-DS2Stream', 
               'Get-DS2ActivationHistory', 'Get-DS2StreamHistory', 
               'Get-DS2StreamVersion', 
               'Get-DatastreamConnectors List-DS2Connectors', 
               'Get-DatastreamDatasetFields List-DS2DatasetFields', 
               'Get-DatastreamGroups List-DS2Groups', 
               'Get-DatastreamProducts List-DS2Products', 
               'Get-DataStreamProperties', 'Get-DataStreams List-DS2Streams', 
               'Get-DataStreamTypes List-DS2StreamTypes', 'New-DS2Stream', 
               'Remove-DS2Stream', 'Set-DS2Stream', 'Get-DiagnosticsGroups', 
               'Get-EdgeLocations', 'Get-IPAccelerationHostnames', 'Get-RecordSets', 
               'Get-TSIGKeys', 'Get-Zones', 'Remove-Zone', 'Get-EdgeKVAccessTokens', 
               'Get-EdgeKVGroups', 'Get-EdgeKVItems', 'Get-EdgeKVNamespaces', 
               'Get-EdgeWorkerActivations', 'Get-EdgeWorkerContracts', 
               'Get-EdgeWorkerDeactivations', 'Get-EdgeWorkerGroups', 
               'Get-EdgeWorkerLimits', 'Get-EdgeWorkerProperties', 
               'Get-EdgeWorkerReports', 'Get-EdgeWorkerResourceTiers', 
               'Get-EdgeWorkers', 'Get-EdgeWorkerVersions', 'Get-FRMCidrBlocks', 
               'Get-FRMServices', 'Get-GTMLivenessTestErrors', 
               'Get-EdgeHostnameChangeRequests', 
               'Get-EdgeHostnameChangeRequestsForHostname', 
               'Get-EdgeHostnameProducts', 'Get-EdgeHostnames', 
               'Get-IDMAccountSwitchKeys', 'Get-IDMGrantableRoles', 
               'Get-IDMGroupMoveAffectedUsers', 'Get-IDMGroups', 'Get-IDMProperties', 
               'Get-IDMPropertyResources', 'Get-IDMRoles', 'Get-IDMUsers', 
               'Get-IDMUsersForProperty', 'Get-ImageManagerImageCollections', 
               'Get-ImageManagerImages', 'Get-ImageManagerPolicies', 
               'Get-LDSContacts', 'Get-LDSDeliveryFrequencies', 
               'Get-LDSDeliveryThresholds', 'Get-LDSLogConfigurations', 
               'Get-LDSLogConfigurationsByType', 'Get-LDSLogConfigurationsForID', 
               'Get-LDSLogEncodings', 'Get-LDSLogFormats', 'Get-LDSLogFormatsByType', 
               'Get-LDSLogRedeliveries', 'Get-LDSLogSources', 
               'Get-LDSLogSourcesByType', 'Get-LDSMessageSizes', 'Get-AMDDataStores', 
               'Get-MSLCDNs', 'Get-MSLContracts', 'Get-MSLCPCodes', 
               'Get-MSLOriginCPCodes', 'Get-MSLOrigins', 
               'Get-MSLPublishingLocations', 'Get-MSLStreams', 'Get-MSLVODOrigins', 
               'Get-NSStorageGroups', 'Get-NSUploadAccounts', 'Get-NSZones', 
               'Get-NetworkLists', 'Get-NetstorageDirectory', 'Get-AllProperties', 
               'Get-BucketActivations', 'Get-BucketHostnames', 
               'Get-BulkActivatedProperties', 'Get-BulkPatchedProperties', 
               'Get-BulkVersionedProperties', 'Get-CustomBehaviors', 'Get-Groups', 
               'Get-PapiContracts', 'Get-PapiCPCodes', 'Get-PapiEdgeHostnames', 
               'Get-Products', 'Get-Properties', 'Get-PropertyActivations', 
               'Get-PropertyHostnames', 'Get-PropertyIncludeActivations', 
               'Get-PropertyIncludes', 'Get-PropertyIncludeVersions', 
               'Get-PropertyVersions', 'Get-RuleFormats', 'Get-TopLevelGroups', 
               'Get-ReportTypes', 'Get-ReportTypeVersions', 'Sanitise-FileName', 
               'Sanitise-QueryString', 'Get-SiteShieldMaps', 
               'Get-SLAAvailabilityReports', 'Get-SLAPerformanceReports', 
               'Get-SLATestAgentGroups', 'Get-SLATestConfigurationQuotas', 
               'Get-SLATestConfigurations', 'Get-TCMSetCertificateIDs', 
               'Get-TCMSetCertificates', 'Get-TCMSets', 'Get-TCMSetTrustChains', 
               'Get-TCMSetVersionCertificateIDs', 'Get-TCMSetVersionCertificates', 
               'Get-TCMSetVersions', 'Get-TestCasesInTestSuite', 
               'Get-TestClientProfiles', 'Get-TestClientProfileTestCases', 
               'Get-TestConditions', 'Get-TestConfigVersions', 'Get-TestDefinitions', 
               'Get-TestExecutions', 'Get-TestRequests', 'Get-TestRequestTestCases', 
               'Get-TestRequirements', 'Get-TestRequirementTestSuites', 
               'Get-TestRuns', 'Get-TestSuiteConfigVersions', 
               'Get-TestSuiteRequirements', 'Get-TestSuites', 
               'Get-TestSuiteTestCases'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/akamai-contrib/akamaipowershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/akamai/akamaipowershell/blob/master/CHANGELOG.md'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIpogYJKoZIhvcNAQcCoIIpkzCCKY8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAnAKsb6MLDKPCE
# WlteozOFj6SCHO0iQhUl4W5vFpoKBKCCDpEwggawMIIEmKADAgECAhAIrUCyYNKc
# TJ9ezam9k67ZMA0GCSqGSIb3DQEBDAUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNV
# BAMTGERpZ2lDZXJ0IFRydXN0ZWQgUm9vdCBHNDAeFw0yMTA0MjkwMDAwMDBaFw0z
# NjA0MjgyMzU5NTlaMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
# ggIKAoICAQDVtC9C0CiteLdd1TlZG7GIQvUzjOs9gZdwxbvEhSYwn6SOaNhc9es0
# JAfhS0/TeEP0F9ce2vnS1WcaUk8OoVf8iJnBkcyBAz5NcCRks43iCH00fUyAVxJr
# Q5qZ8sU7H/Lvy0daE6ZMswEgJfMQ04uy+wjwiuCdCcBlp/qYgEk1hz1RGeiQIXhF
# LqGfLOEYwhrMxe6TSXBCMo/7xuoc82VokaJNTIIRSFJo3hC9FFdd6BgTZcV/sk+F
# LEikVoQ11vkunKoAFdE3/hoGlMJ8yOobMubKwvSnowMOdKWvObarYBLj6Na59zHh
# 3K3kGKDYwSNHR7OhD26jq22YBoMbt2pnLdK9RBqSEIGPsDsJ18ebMlrC/2pgVItJ
# wZPt4bRc4G/rJvmM1bL5OBDm6s6R9b7T+2+TYTRcvJNFKIM2KmYoX7BzzosmJQay
# g9Rc9hUZTO1i4F4z8ujo7AqnsAMrkbI2eb73rQgedaZlzLvjSFDzd5Ea/ttQokbI
# YViY9XwCFjyDKK05huzUtw1T0PhH5nUwjewwk3YUpltLXXRhTT8SkXbev1jLchAp
# QfDVxW0mdmgRQRNYmtwmKwH0iU1Z23jPgUo+QEdfyYFQc4UQIyFZYIpkVMHMIRro
# OBl8ZhzNeDhFMJlP/2NPTLuqDQhTQXxYPUez+rbsjDIJAsxsPAxWEQIDAQABo4IB
# WTCCAVUwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUaDfg67Y7+F8Rhvv+
# YXsIiGX0TkIwHwYDVR0jBBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0P
# AQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUFBwMDMHcGCCsGAQUFBwEBBGswaTAk
# BggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAC
# hjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9v
# dEc0LmNydDBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5j
# b20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNybDAcBgNVHSAEFTATMAcGBWeBDAED
# MAgGBmeBDAEEATANBgkqhkiG9w0BAQwFAAOCAgEAOiNEPY0Idu6PvDqZ01bgAhql
# +Eg08yy25nRm95RysQDKr2wwJxMSnpBEn0v9nqN8JtU3vDpdSG2V1T9J9Ce7FoFF
# UP2cvbaF4HZ+N3HLIvdaqpDP9ZNq4+sg0dVQeYiaiorBtr2hSBh+3NiAGhEZGM1h
# mYFW9snjdufE5BtfQ/g+lP92OT2e1JnPSt0o618moZVYSNUa/tcnP/2Q0XaG3Ryw
# YFzzDaju4ImhvTnhOE7abrs2nfvlIVNaw8rpavGiPttDuDPITzgUkpn13c5Ubdld
# AhQfQDN8A+KVssIhdXNSy0bYxDQcoqVLjc1vdjcshT8azibpGL6QB7BDf5WIIIJw
# 8MzK7/0pNVwfiThV9zeKiwmhywvpMRr/LhlcOXHhvpynCgbWJme3kuZOX956rEnP
# LqR0kq3bPKSchh/jwVYbKyP/j7XqiHtwa+aguv06P0WmxOgWkVKLQcBIhEuWTatE
# QOON8BUozu3xGFYHKi8QxAwIZDwzj64ojDzLj4gLDb879M4ee47vtevLt/B3E+bn
# KD+sEq6lLyJsQfmCXBVmzGwOysWGw/YmMwwHS6DTBwJqakAwSEs0qFEgu60bhQji
# WQ1tygVQK+pKHJ6l/aCnHwZ05/LWUpD9r4VIIflXO7ScA+2GRfS0YW6/aOImYIbq
# yK+p/pQd52MbOoZWeE4wggfZMIIFwaADAgECAhAHzYbPdL0G4DP0mj8QhQwXMA0G
# CSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwg
# SW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBDb2RlIFNpZ25pbmcg
# UlNBNDA5NiBTSEEzODQgMjAyMSBDQTEwHhcNMjMwMTExMDAwMDAwWhcNMjQwMzAy
# MjM1OTU5WjCB3jETMBEGCysGAQQBgjc8AgEDEwJVUzEZMBcGCysGAQQBgjc8AgEC
# EwhEZWxhd2FyZTEdMBsGA1UEDwwUUHJpdmF0ZSBPcmdhbml6YXRpb24xEDAOBgNV
# BAUTBzI5MzM2MzcxCzAJBgNVBAYTAlVTMRYwFAYDVQQIEw1NYXNzYWNodXNldHRz
# MRIwEAYDVQQHEwlDYW1icmlkZ2UxIDAeBgNVBAoTF0FrYW1haSBUZWNobm9sb2dp
# ZXMgSW5jMSAwHgYDVQQDExdBa2FtYWkgVGVjaG5vbG9naWVzIEluYzCCAiIwDQYJ
# KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKkC2pEjLYnjLtkW+Vkz3mCe+wElX+k7
# AgEtGOL+rqaYNF9CdS8veLyZY6fQeq/ugDkdGuKdz0oXGlzTaVgnOcd1TZrVSeVR
# KiE9/gO1mSP/kuyJPKFMDUNR4LE5+j5chSCyLoKhmsAFdus/KH6ZizjcM4rtTkNs
# 714lHQ91LssdoX+rZXhn/ttsiEtOG4dAZdntDv4aDjI/lde5DouV9k/ISKPTrvmF
# obsrEUxqfOwynq8yqVaQMABw8aeA0ajU6EgD+4gGG8TaFNxQZOPgAZNWYpqwbnlR
# f35mgl4HufEPVaHwN8158jpippKW7iUFTvV5zpmcd6T1DMWtoePcRLm/unvosA0g
# DHn/hZO+GdQ4IbJ70oObq497Xwp02iGP4b/dNHQF3XV92Y262v0c1WkaAVAOHMFP
# nJVp7FAUS2I3Zfqu/R2ZjSUfXPtWg2ar+HGZ4tAnc6Zd5uS+Ggyf5jUA2rz9r0wT
# fxei07j2A1F5/kvpUMevzkEE2aWWeKQrqiSIPT48j2VoMM9zQD3v7tGvzAHk9SSi
# SSOM6NZWwDROdTSXn5pCNzEwfy7OinP33qSZWC1Omx3GNPtHVGcBGOZCwbNBiz2i
# EwR4HyJvuxZjeam5dM5zuuCoyYrxLINVlcLFpbg7uAMaM0WTf52/SB2040aDeSzi
# kVgXUiWy9MnxAgMBAAGjggIFMIICATAfBgNVHSMEGDAWgBRoN+Drtjv4XxGG+/5h
# ewiIZfROQjAdBgNVHQ4EFgQUAgywME/nFo30YHtViHhRyLCj41MwDgYDVR0PAQH/
# BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMIG1BgNVHR8Ega0wgaowU6BRoE+G
# TWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNENvZGVT
# aWduaW5nUlNBNDA5NlNIQTM4NDIwMjFDQTEuY3JsMFOgUaBPhk1odHRwOi8vY3Js
# NC5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRDb2RlU2lnbmluZ1JTQTQw
# OTZTSEEzODQyMDIxQ0ExLmNybDA9BgNVHSAENjA0MDIGBWeBDAEDMCkwJwYIKwYB
# BQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCBlAYIKwYBBQUHAQEE
# gYcwgYQwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBcBggr
# BgEFBQcwAoZQaHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1
# c3RlZEc0Q29kZVNpZ25pbmdSU0E0MDk2U0hBMzg0MjAyMUNBMS5jcnQwDAYDVR0T
# AQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAqItOsemfwmwzLKUyPRVuyuXhMpWM
# iHQqfsSloP6KdVwtTMQBP1lmxsE1qAQ3R52iCiGAra7dvZRUm3mWXTntXQwXUEqH
# dguy53+VrZ7f+BtZiL51OJOJXyiy3lSA+rrr7g1Xuz2ax+tRLqkmmOswYoPSnSIc
# EhGyaoLKFX19/agk6tiZzVdzbz5N/aPFKAng0BkilTvSI8JJDHyO2lxhHzZ3zPFf
# 51pxBn7+HkeRdLQ2aSy4j8Y8P2sMWPOhs2EjDJ14wHZIPHMHorI40AnPVOQjJ1h1
# ME/eh2HVCQMf1BIDc7ZXkHX6mW6BbLxTuWhxiPcTKvj3/HO+VyeEjTgT0+NHCEiQ
# +LFudP/MYR7T8Vy2Zsg0HnNXAsC2JjDLLu/Ce69Xlh3ntc0jiQtT0X38ZMXwUSA+
# 7jgNe93Wx4GLjzw9MfOXYwqRAWC2dUXcUWKUHGpreX4wRQjemFMifnaEOfWJZZ5w
# mkGJkfh0XmVfFFg4aE6LidoqcKvlXfpzNxEsBTJUeETPdaiYHhJT5M7YgQiAuJd6
# bQj67m/lutkBz5ucXuOSte3wddC4PmFMCkrJ/3ZLk5se0Tcq1+Zxj2IDNXUkO14p
# 0lGr0mLiEBXIJB0/RTdrCNQXTgfBfm/2JGm11XnKxWYr7iRxZwWjh5V/FJYO6kHc
# JZzQBtUCg02o9ogxghpnMIIaYwIBATB9MGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQK
# Ew5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBD
# b2RlIFNpZ25pbmcgUlNBNDA5NiBTSEEzODQgMjAyMSBDQTECEAfNhs90vQbgM/Sa
# PxCFDBcwDQYJYIZIAWUDBAIBBQCgfDAQBgorBgEEAYI3AgEMMQIwADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAvBgkqhkiG9w0BCQQxIgQgltr3LiE5Xb8qk/ZrZdf0JF2mwNb2wp0eAWHEd8sC
# UM0wDQYJKoZIhvcNAQEBBQAEggIAH0Ce91pUkDn+o0P1kn8MmjsGOCD9GVg6AI1q
# tVkAx9DyvnHrBIQ45FVgKPe322pgNqwIWMC960msmZ5v6at6bht1TDkSYXNK+Tri
# kDoFnGiUOd1Uu2oSxDswLXyZWX/og0niL9amCB9cilj00ME1YKEa5wHdx0JLaPJs
# NNeNJ9D1RGQO19TopkfFCTONnY7tEU+1l/ggZguSpeelkuHSZ8Yh5unZ5HeoJJI/
# WfxSThWMnKWcGdgR8NPB/gpWMae1ZN6UNrwtIOmoxSI5ebFil0r1edSW52civq/N
# zsFMHL5J0XRo/Wv8pfU9QEilX1clUnhx9PY4ZBO+2n9gidQol5eFYpFeZ3oB+ZFy
# 51tVxe/5NL1Mw9/S91gg67eXT6aVCyEx+j5/T+MPqH+dGaEY2fgh6ABp8GoH2gyd
# dXyH/2w+QfSefTVmePJmxKqmAKHRzQOvGqQwsO0Sj8a8R940Qg5rQLbXQAgPVyGy
# YhQr083SvXBMZtYt1z2njxmLjs5h8GpBGrLCZKdADXr7WxDgOBDVR4YsTN3qdV2D
# 1YN7PtMdllmd64kLoxEW2XExy3V1E1hUa1CYU8DtDtLeExZ4caJtQkt0u5PIY6YA
# sC6ZvhPl5rMKJRpJM4qM/Cs1avnyAqQ3oAqumU3RRwCGPcMCet10arnLXQ1N60BK
# 4p5iGjGhghc9MIIXOQYKKwYBBAGCNwMDATGCFykwghclBgkqhkiG9w0BBwKgghcW
# MIIXEgIBAzEPMA0GCWCGSAFlAwQCAQUAMHcGCyqGSIb3DQEJEAEEoGgEZjBkAgEB
# BglghkgBhv1sBwEwMTANBglghkgBZQMEAgEFAAQgl5YYbMZCDWIJlzaig8n9JT+P
# 7Qx8/v324ULXIcxUclgCEAZ5+Wg+sSqRXGl11izMyigYDzIwMjMwNDI1MTgxNjI5
# WqCCEwcwggbAMIIEqKADAgECAhAMTWlyS5T6PCpKPSkHgD1aMA0GCSqGSIb3DQEB
# CwUAMGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjE7MDkG
# A1UEAxMyRGlnaUNlcnQgVHJ1c3RlZCBHNCBSU0E0MDk2IFNIQTI1NiBUaW1lU3Rh
# bXBpbmcgQ0EwHhcNMjIwOTIxMDAwMDAwWhcNMzMxMTIxMjM1OTU5WjBGMQswCQYD
# VQQGEwJVUzERMA8GA1UEChMIRGlnaUNlcnQxJDAiBgNVBAMTG0RpZ2lDZXJ0IFRp
# bWVzdGFtcCAyMDIyIC0gMjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AM/spSY6xqnya7uNwQ2a26HoFIV0MxomrNAcVR4eNm28klUMYfSdCXc9FZYIL2tk
# pP0GgxbXkZI4HDEClvtysZc6Va8z7GGK6aYo25BjXL2JU+A6LYyHQq4mpOS7eHi5
# ehbhVsbAumRTuyoW51BIu4hpDIjG8b7gL307scpTjUCDHufLckkoHkyAHoVW54Xt
# 8mG8qjoHffarbuVm3eJc9S/tjdRNlYRo44DLannR0hCRRinrPibytIzNTLlmyLuq
# UDgN5YyUXRlav/V7QG5vFqianJVHhoV5PgxeZowaCiS+nKrSnLb3T254xCg/oxwP
# UAY3ugjZNaa1Htp4WB056PhMkRCWfk3h3cKtpX74LRsf7CtGGKMZ9jn39cFPcS6J
# AxGiS7uYv/pP5Hs27wZE5FX/NurlfDHn88JSxOYWe1p+pSVz28BqmSEtY+VZ9U0v
# kB8nt9KrFOU4ZodRCGv7U0M50GT6Vs/g9ArmFG1keLuY/ZTDcyHzL8IuINeBrNPx
# B9ThvdldS24xlCmL5kGkZZTAWOXlLimQprdhZPrZIGwYUWC6poEPCSVT8b876asH
# DmoHOWIZydaFfxPZjXnPYsXs4Xu5zGcTB5rBeO3GiMiwbjJ5xwtZg43G7vUsfHuO
# y2SJ8bHEuOdTXl9V0n0ZKVkDTvpd6kVzHIR+187i1Dp3AgMBAAGjggGLMIIBhzAO
# BgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEF
# BQcDCDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwHwYDVR0jBBgw
# FoAUuhbZbU2FL3MpdpovdYxqII+eyG8wHQYDVR0OBBYEFGKK3tBh/I8xFO2XC809
# KpQU31KcMFoGA1UdHwRTMFEwT6BNoEuGSWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdDQS5j
# cmwwgZAGCCsGAQUFBwEBBIGDMIGAMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5k
# aWdpY2VydC5jb20wWAYIKwYBBQUHMAKGTGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0
# LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdD
# QS5jcnQwDQYJKoZIhvcNAQELBQADggIBAFWqKhrzRvN4Vzcw/HXjT9aFI/H8+ZU5
# myXm93KKmMN31GT8Ffs2wklRLHiIY1UJRjkA/GnUypsp+6M/wMkAmxMdsJiJ3Hjy
# zXyFzVOdr2LiYWajFCpFh0qYQitQ/Bu1nggwCfrkLdcJiXn5CeaIzn0buGqim8FT
# YAnoo7id160fHLjsmEHw9g6A++T/350Qp+sAul9Kjxo6UrTqvwlJFTU2WZoPVNKy
# G39+XgmtdlSKdG3K0gVnK3br/5iyJpU4GYhEFOUKWaJr5yI+RCHSPxzAm+18SLLY
# kgyRTzxmlK9dAlPrnuKe5NMfhgFknADC6Vp0dQ094XmIvxwBl8kZI4DXNlpflhax
# YwzGRkA7zl011Fk+Q5oYrsPJy8P7mxNfarXH4PMFw1nfJ2Ir3kHJU7n/NBBn9iYy
# mHv+XEKUgZSCnawKi8ZLFUrTmJBFYDOA4CPe+AOk9kVH5c64A0JH6EE2cXet/aLo
# l3ROLtoeHYxayB6a1cLwxiKoT5u92ByaUcQvmvZfpyeXupYuhVfAYOd4Vn9q78KV
# mksRAsiCnMkaBXy6cbVOepls9Oie1FqYyJ+/jbsYXEP10Cro4mLueATbvdH7Wwqo
# cH7wl4R44wgDXUcsY6glOJcB0j862uXl9uab3H4szP8XTE0AotjWAQ64i+7m4HJV
# iSwnGWH2dwGMMIIGrjCCBJagAwIBAgIQBzY3tyRUfNhHrP0oZipeWzANBgkqhkiG
# 9w0BAQsFADBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkw
# FwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBUcnVz
# dGVkIFJvb3QgRzQwHhcNMjIwMzIzMDAwMDAwWhcNMzcwMzIyMjM1OTU5WjBjMQsw
# CQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRp
# Z2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEyNTYgVGltZVN0YW1waW5nIENB
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxoY1BkmzwT1ySVFVxyUD
# xPKRN6mXUaHW0oPRnkyibaCwzIP5WvYRoUQVQl+kiPNo+n3znIkLf50fng8zH1AT
# CyZzlm34V6gCff1DtITaEfFzsbPuK4CEiiIY3+vaPcQXf6sZKz5C3GeO6lE98NZW
# 1OcoLevTsbV15x8GZY2UKdPZ7Gnf2ZCHRgB720RBidx8ald68Dd5n12sy+iEZLRS
# 8nZH92GDGd1ftFQLIWhuNyG7QKxfst5Kfc71ORJn7w6lY2zkpsUdzTYNXNXmG6jB
# ZHRAp8ByxbpOH7G1WE15/tePc5OsLDnipUjW8LAxE6lXKZYnLvWHpo9OdhVVJnCY
# Jn+gGkcgQ+NDY4B7dW4nJZCYOjgRs/b2nuY7W+yB3iIU2YIqx5K/oN7jPqJz+ucf
# WmyU8lKVEStYdEAoq3NDzt9KoRxrOMUp88qqlnNCaJ+2RrOdOqPVA+C/8KI8ykLc
# GEh/FDTP0kyr75s9/g64ZCr6dSgkQe1CvwWcZklSUPRR8zZJTYsg0ixXNXkrqPNF
# YLwjjVj33GHek/45wPmyMKVM1+mYSlg+0wOI/rOP015LdhJRk8mMDDtbiiKowSYI
# +RQQEgN9XyO7ZONj4KbhPvbCdLI/Hgl27KtdRnXiYKNYCQEoAA6EVO7O6V3IXjAS
# vUaetdN2udIOa5kM0jO0zbECAwEAAaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8C
# AQAwHQYDVR0OBBYEFLoW2W1NhS9zKXaaL3WMaiCPnshvMB8GA1UdIwQYMBaAFOzX
# 44LScV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggr
# BgEFBQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3Nw
# LmRpZ2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0cDovL2NhY2VydHMuZGlnaWNl
# cnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcnQwQwYDVR0fBDwwOjA4oDag
# NIYyaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RH
# NC5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZIAYb9bAcBMA0GCSqGSIb3
# DQEBCwUAA4ICAQB9WY7Ak7ZvmKlEIgF+ZtbYIULhsBguEE0TzzBTzr8Y+8dQXeJL
# Kftwig2qKWn8acHPHQfpPmDI2AvlXFvXbYf6hCAlNDFnzbYSlm/EUExiHQwIgqgW
# valWzxVzjQEiJc6VaT9Hd/tydBTX/6tPiix6q4XNQ1/tYLaqT5Fmniye4Iqs5f2M
# vGQmh2ySvZ180HAKfO+ovHVPulr3qRCyXen/KFSJ8NWKcXZl2szwcqMj+sAngkSu
# mScbqyQeJsG33irr9p6xeZmBo1aGqwpFyd/EjaDnmPv7pp1yr8THwcFqcdnGE4AJ
# xLafzYeHJLtPo0m5d2aR8XKc6UsCUqc3fpNTrDsdCEkPlM05et3/JWOZJyw9P2un
# 8WbDQc1PtkCbISFA0LcTJM3cHXg65J6t5TRxktcma+Q4c6umAU+9Pzt4rUyt+8SV
# e+0KXzM5h0F4ejjpnOHdI/0dKNPH+ejxmF/7K9h+8kaddSweJywm228Vex4Ziza4
# k9Tm8heZWcpw8De/mADfIBZPJ/tgZxahZrrdVcA6KYawmKAr7ZVBtzrVFZgxtGIJ
# Dwq9gdkT/r+k0fNX2bwE+oLeMt8EifAAzV3C+dAjfwAL5HYCJtnwZXZCpimHCUcr
# 5n8apIUP/JiW9lVUKx+A+sDyDivl1vupL0QVSucTDh3bNzgaoSv27dZ8/DCCBY0w
# ggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJKoZIhvcNAQEMBQAwZTELMAkG
# A1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRp
# Z2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNzdXJlZCBJRCBSb290IENB
# MB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1OVowYjELMAkGA1UEBhMCVVMx
# FTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNv
# bTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBSb290IEc0MIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+RdSjwwIjBpM+zCpyUuySE98orY
# WcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20dq7J58soR0uRf1gU8Ug9SH8ae
# FaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7fgvMHhOZ0O21x4i0MG+4g1ckg
# HWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRAX7F6Zu53yEioZldXn1RYjgwr
# t0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raRmECQecN4x7axxLVqGDgDEI3Y
# 1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzUvK4bA3VdeGbZOjFEmjNAvwjX
# WkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2mHY9WV1CdoeJl2l6SPDgohIb
# Zpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkrfsCUtNJhbesz2cXfSwQAzH0c
# lcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaAsPvoZKYz0YkH4b235kOkGLim
# dwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxfjT/JvNNBERJb5RBQ6zHFynIW
# IgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEexcCPorF+CiaZ9eRpL5gdLfXZ
# qbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOzX
# 44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaAFEXroq/0ksuCMS1Ri6enIZ3z
# bcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcBAQRtMGswJAYIKwYBBQUHMAGG
# GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2Nh
# Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNydDBF
# BgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNl
# cnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQKMAgwBgYEVR0gADANBgkqhkiG
# 9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3v1cHvZqsoYcs7IVeqRq7IviH
# GmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy3iS8UgPITtAq3votVs/59Pes
# MHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cnRNTnf+hZqPC/Lwum6fI0POz3
# A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3WlxUjG/voVA9/HYJaISfb8rb
# II01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2zm8jLfR+cWojayL/ErhULSd+
# 2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDGCA3YwggNyAgEBMHcwYzELMAkG
# A1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQDEzJEaWdp
# Q2VydCBUcnVzdGVkIEc0IFJTQTQwOTYgU0hBMjU2IFRpbWVTdGFtcGluZyBDQQIQ
# DE1pckuU+jwqSj0pB4A9WjANBglghkgBZQMEAgEFAKCB0TAaBgkqhkiG9w0BCQMx
# DQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTIzMDQyNTE4MTYyOVowKwYL
# KoZIhvcNAQkQAgwxHDAaMBgwFgQU84ciTYYzgpI1qZS8vY+W6f4cfHMwLwYJKoZI
# hvcNAQkEMSIEIOkEBwO323PvbUFO4vggm9WwOmdFpnnwkmJ6ieYz15LZMDcGCyqG
# SIb3DQEJEAIvMSgwJjAkMCIEIMf04b4yKIkgq+ImOr4axPxP5ngcLWTQTIB1V6Aj
# tbb6MA0GCSqGSIb3DQEBAQUABIICAKXKX+wogislVPVEGBe2a7YrH8W0GmX6qqWQ
# WbseaHxaH8oVqfW29AwqCNY9QXhgMebkpffFoTaj/kCtmsbBOgZRC2hONpD5JFNN
# qYpIZ5NJdjcF6dgGw8eOiecxWQNxlSiTWHylmPwL26bkBkIpXivFwwl2evMfVw0N
# MEmDsAXdhGn80sWiStl1e9BeMS19Fw6stm7ypd8TLHYMLhKDGGtyVqLlWNOMQ4D5
# KfArEJldhnD04Mlt312CzIT8xfum8XqpG2Xutd4nxVAbStbnx9G8fXvUgFKTteVS
# CFRYSPmnZEpD/SzctbqY1OQkPzisSy2B0Xx7Cmk7MILrs+jMmsmPuTbLwT9kAUBx
# NP0iuKCZZ752G3BbEH7EH2C2v8x5fgitlARQc8q7ReMjdLw95TChXr6a9dPLzs/+
# viD2x8tEhkJrDLJFc61QudTDTbFbBEScluCPZkMosA210u4aL1aYxYh8OKxy0w8R
# TsozR/uvY3u0XrkYaC7aNpYslo17/66gBYpcMcmvFU086v8+MOCwlMlUp2W7QcH+
# nItxek4W1VvhRfzsLCV1PHjwk2fFIMwDzv1rIU2QKingWHTHrCWKPEPDyQj0YsKq
# ly0rEqq5wqoCGqExNsJMUYfD8KyA9mQzS87l8GYqN8HxWyfUinGxPOCZlOUdwZb2
# 2w1V3Z0t
# SIG # End signature block
